### ISSUE TITLE
xmlpoke sync

### ISSUE THREAD

**Issue by Alphapage** [mikeobrien/node-xmlpoke#1]
Hello,

It would be great to have a sync way without callback , something like this:

```
xmlpokeSync('proj.config').set('some/path', 'value')
```

Is it possible ?

Thanks in advance for your answer.

**Comment by mikeobrien** [comment]
It actually is synchronous. It's a HoF so that it can wrap your functionality with the load and save. Otherwise you'd have to explicitly call these before and after.
