### ISSUE TITLE
jsonpoke

### ISSUE THREAD

**Issue by fpereira1** [mikeobrien/node-xmlpoke#2]
Cool library, I just used to update the XML for my firefox extension using gulp after I run `npm version patch`.

do you plan to work on a `jsonpoke` library too? I think that would be really useful.  If you don't have any plans I think that's something I could invest some time to work on.

Thanks

**Comment by mikeobrien** [comment]
Naw, no plans for that. Probably wouldn't be that difficult to do tho, good idea!

**Comment by fpereira1** [comment]
I didn't have a look at that as I think javascript object manipulation is pretty easy with existing stuff.  So closing as question answered
